### ISSUE TITLE
Bug quand on casse des blocks avec une pioche non silktouch

### ISSUE THREAD

**Issue by SteelJim** [Achent007/Arkheris#43]
**Décris le bug**
Quand on casse un bloc avec une pioche NON SILKTOUCH, on obtient le drop du bloc comme si elle était silk touch

**Coordonées du bug**
partout

**Screenshots / Vidéos**
https://youtu.be/tQ99GGyxgB0

**Informations complémentaires**
nope

**Comment by Achent007** [comment]
Soucis de permissions (fixé au prochaine redémarrage)
